apiVersion: v1
kind: Service
metadata:
  name: nginx-alpine
  namespace: {{ .Values.namespace.name }} 
  labels:
    app: nginx
    tag: alpine
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }} 
  selector:
    app: nginx
    tag: alpine