namespace:
  name: prod
replicaCount: 2
service:
  port: 80
  type: ClusterIP
image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 70m
    mem: 256Mi
configmap:
  data: "version: 1.17.0"